name: Dripyard Neonbyte Canvas Patterns
type: Dripyard
description: 'Provides component patterns for Drupal Canvas using Neonbyte theme'
install:
  - canvas
config:
  strict: false
recipes:
  - 'dripyard_canvas_patterns'
