name: Dripyard Card Block
type: Dripyard
description: 'Provides a card block type with title, link, and media.'
install:
  - block_content
config:
  strict: false
recipes:
  - 'dripyard_media'
  - 'dripyard_fields_block'
